variable_name: 
    min_length: 
        warning: 1
        error: 0

force_try: warning

opt_in_rules:
  - vertical_whitespace
    
disabled_rules: # rule identifiers to exclude from running
  - function_body_length
  - line_length

reporter: "json"
