variable_name:
    min_length:
        warning: 1
        error: 0

colon:
  apply_to_dictionaries: false

force_try: warning

opt_in_rules:
  - vertical_whitespace
  - closure_spacing

disabled_rules: # rule identifiers to exclude from running
  - function_body_length
  - line_length
  - trailing_comma

reporter: "json"
