version: 2

jobs:
  build930:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run: sudo gem install danger
      - run: brew update
      - run: brew outdated swiftlint || brew upgrade swiftlint
      - run: swiftlint lint --quiet | tee lintreport.json || true # Dont crash on errors
      - run: ./xswift-test-spm
      - run: 
          name: Danger Systems
          when: on_success
          command: danger || true # Dont fail build on non zero exit codes
  build920:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: ./xswift-test-spm
  build910:
    macos:
      xcode: "9.1.0"
    steps:
      - checkout
      - run: ./xswift-test-spm
  build901:
    macos:
      xcode: "9.0.1"
    steps:
      - checkout
      - run: ./xswift-test-spm
workflows:
  version: 2
  workflow:
    jobs:
      - build901
      - build910
      - build920
      - build930
