version: 2

jobs:
  build92:
    macos:
      xcode: "9.2"
    steps:
      - checkout
      - run: sudo gem install danger
      - run: brew update
      - run: brew outdated swiftlint || brew upgrade swiftlint
      - run: swiftlint lint --quiet | tee lintreport.json || true # Dont crash on errors
      - run: ./xswift-test-spm
      - run: 
          name: Danger Systems
          when: on_success
          command: danger || true # Dont fail build on non zero exit codes
  build91:
    macos:
      xcode: "9.1"
    steps:
      - checkout
      - run: ./xswift-test-spm
  build90:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: ./xswift-test-spm
workflows:
  version: 2
  workflow:
    jobs:
      - build90
      - build91
      - build92
